### ISSUE TITLE
Odd Rollup Error

### ISSUE THREAD

**Issue by Paul-Hebert** [cloudfour/eleventy-patterns#27]
When saving javascript files this error happens frequently:

```log
[13:47:07] Starting 'js'...
[13:47:07] 'js' errored after 13 ms
[13:47:07] Error in plugin "gulp-better-rollup"
Message:
    Could not load /Users/paulhebert/repos/Eleventy-Patterns/src/scripts/_46__46__47_patterns_47__42__42__47__42__46_js (imported by /Users/paulhebert/repos/Eleventy-Patterns/src/scripts/toolkit.js): ENOENT: no such file or directory, open '/Users/paulhebert/repos/Eleventy-Patterns/src/scripts/_46__46__47_patterns_47__42__42__47__42__46_js'
Details:
    errno: -2
    code: PLUGIN_ERROR
    syscall: open
    path: /Users/paulhebert/repos/Eleventy-Patterns/src/scripts/_46__46__47_patterns_47__42__42__47__42__46_js
    pluginCode: ENOENT
    hook: load
    domainEmitter: [object Object]
    domain: [object Object]
    domainThrown: false
```

Oddly, resaving the file a second time usually resolves it. 

It appears this is related to the glob importing we're using to import pattern JS:

```js
// eslint-disable-next-line no-unused-vars
import * as patterns from '../patterns/**/*.js';
```

**Comment by tylersticka** [comment]
In the past @calebeby has offered helpful advice when it comes to Rollup configuration. Tagging him in case he looks at this and sees something obvious we might otherwise miss.

**Comment by calebeby** [comment]
This is not an error I have seen before. I suspect it is not an error with Rollup itself, but with https://github.com/kei-ito/rollup-plugin-glob-import.

I wonder if switching from using that rollup plugin to [this babel plugin](https://github.com/novemberborn/babel-plugin-import-glob) would make the error go away? It looks like that babel-based approach is more straightforward and less bug prone than the way that the rollup plugin works.

**Comment by Paul-Hebert** [comment]
Awesome, thanks @calebeby ! I'll give it a try 😁
