### ISSUE TITLE
Simplify/unify "new" tasks

### ISSUE THREAD

**Issue by tylersticka** [cloudfour/eleventy-patterns#3]
The `npx gulp newPrototype` and `npx gulp newPattern` tasks are awesome!

I wonder if it would be possible to simplify that syntax at all to make them a little easier to remember?

This may not be possible/feasible, but in a perfect world...

- `npm run new`: Asks what new thing you want to make.
- `npm run new pattern`
- `npm run new prototype`

Just a thought, happy for others to disagree!

**Comment by Paul-Hebert** [comment]
Makes sense to me! Seems like it might make the code more DRY as well!

**Comment by Paul-Hebert** [comment]
In an unrelated PR `newPattern` and `newPrototype` were renamed to `pattern` and `prototype` but Tyler's point still stands. We should do this!
