### ISSUE TITLE
Support for more helper types

### ISSUE THREAD

**Issue by tylersticka** [cloudfour/eleventy-patterns#4]
I tried adding some helpers and I was a little confused initially.

We currently have everything in `helpers/filter`, but all of these are added using `eleventyConfig.addHandlebarsHelper`. I didn't expect this to be the case!

This makes it difficult to add universal [filters](https://www.11ty.dev/docs/filters/) and [shortcodes](https://www.11ty.dev/docs/shortcodes/). It'd be really cool to be able to add those sorts of things with some prototyping tools baked in that would work regardless of the project's template engine.

Ideally, this directory would be separated based on all the helpers Eleventy supports, so you could do something like this:

```
helpers
├── filters
├── handlebars-helpers
├── liquid-tags
└── shortcodes
```

**Comment by Paul-Hebert** [comment]
Ahh yeah, makes sense! Good call. You're right that this will be more
important as we add more templating options!
