### ISSUE TITLE
Placeholder data or helpers

### ISSUE THREAD

**Issue by tylersticka** [cloudfour/eleventy-patterns#6]
In our [Handlebars helpers](https://github.com/cloudfour/core-hbs-helpers), there are two helpers we've used for FPO or dummy content:

- [`dummyImgSrc`](https://github.com/cloudfour/core-hbs-helpers/blob/master/lib/dummyImgSrc.js)
- [`random`](https://github.com/cloudfour/core-hbs-helpers/blob/master/lib/random.js) (but Eleventy warns that this is a performance hog)

We've also used other techniques for this:

- [A file with typographic samples](https://github.com/cloudfour/cloudfour.com-patterns/blob/master/src/data/specimens.yml)
- Various image placeholder services

It'd be neat to ship this boilerplate with _some_ sort of FPO content strategy for rapid prototyping. That might be as simple as a `placeholder.json` data file with headings and paragraphs in it, or maybe there's an alternative approach to our previous helpers that could provide some universal capabilities like that.

**Comment by Paul-Hebert** [comment]
Totally. I was planning on adding the `core-hbs-helpers` when I have some
time but it sounds like there may be some performance concerns there? I
find a lot of those handy but want to keep the project quick. I'll have to
do some more research...

**Comment by tylersticka** [comment]
@Paul-Hebert Another drawback of `core-hbs-helpers` is that it's Handlebars-specific. If we add helpers as universal shortcodes or filters, they'll work regardless of the template engine!

**Comment by Paul-Hebert** [comment]
That's a good point!
