### ISSUE TITLE
Enforce at least some code style

### ISSUE THREAD

**Issue by tylersticka** [cloudfour/eleventy-patterns#8]
I don't know which styles are too opinionated for a project boilerplate, but I'd love to at least have enforcement of tabs and stuff via `editorconfig` if possible?

But I'd also be open to `eslint` and `stylelint` configs.

**Comment by Paul-Hebert** [comment]
>I don't know which styles are too opinionated for a project boilerplate

If you have some time I'd love to chat about this more. I've got a branch
where I'm adding linting and it's mostly done but I was starting to
question how opinionated to get.

**Comment by Paul-Hebert** [comment]
This is where that work is currently at: https://github.com/cloudfour/eleventy-patterns/compare/add-linting?expand=1

**Comment by tylersticka** [comment]
@Paul-Hebert I just assigned you to this since it's already in progress!

I defer to the recommendation that you and others in @cloudfour/dev have.

**Comment by Paul-Hebert** [comment]
This was addressed in #12
