### ISSUE TITLE
Re-organize and scrutinize helpers

### ISSUE THREAD

**Issue by tylersticka** [cloudfour/eleventy-patterns#9]
The current set of Handlebars helpers needs some re-organization and cleanup since resolving #4. Some examples:

- `consoleLog` is probably not necessary since [`{{ log }}`](https://handlebarsjs.com/guide/builtin-helpers.html#log) exists
- `markdown` uses a different Markdown library than Eleventy, resulting in potential inconsistencies between the output of Markdown depending on where it is compiled.
- Most (possibly all) of the helpers would work as universal filters or shortcodes in Eleventy, which would make them easier to use in more projects.

**Comment by Paul-Hebert** [comment]
That all makes sense. Thanks Tyler!
